In [3]:
# Gaussian Elimination
import numpy as np
from myMath.linear_algebra import linear_system_solver
linear_solver=linear_system_solver()
A=np.array([[12,2,0],[1,8,2],[1,5,10]])
b=np.array([1,2,3])
x=linear_solver.gaussian_elimination(A,b)
print(x)


[0.06547619 0.10714286 0.125     ]


In [2]:
# Jacobi method:

import numpy as np
from myMath.linear_algebra import linear_system_solver
linear_solver=linear_system_solver()
A=np.array([[12,2,0],[1,8,2],[1,5,10]])
b=np.array([1,2,3])
x=linear_solver.jacobi(A,b)
print(x)
print(np.matmul(A,x))

[0.05096992 0.19417217 0.1978124 ]
[0.99998341 1.99997208 2.99995478]


In [1]:
# Gauss-Seidel method:

import numpy as np
from myMath.linear_algebra import linear_system_solver
linear_solver=linear_system_solver()
A=np.array([[12,2,0],[1,8,2],[1,5,10]])
b=np.array([1,2,3])
x=linear_solver.gauss_seidel(A,b)
print(x)
print(np.matmul(A,x))

[0.05097068 0.19417488 0.19781549]
[0.99999793 2.00000071 3.        ]


In [2]:
# LU decomposition
import numpy as np
from myMath.linear_algebra import linear_system_solver
A=np.array([[3,0,1],[2,10,3],[1,0,8]])
linear_solver=linear_system_solver()
L,U=linear_solver.LU(A)
print(L)
print(U)
print(np.matmul(L,U))

[[1.         0.         0.        ]
 [0.66666667 1.         0.        ]
 [0.33333333 0.         1.        ]]
[[ 3.          0.          1.        ]
 [ 0.         10.          2.33333333]
 [ 0.          0.          7.66666667]]
[[ 3.  0.  1.]
 [ 2. 10.  3.]
 [ 1.  0.  8.]]


In [2]:
# solve a linear system using LU decomposition
from myMath.linear_algebra import linear_system_solver
import numpy as np
A=np.array([[3,0,1],[2,10,3],[1,0,8]])
b=np.array([1.2,2.4,5.6])
linear_solver=linear_system_solver()
x=linear_solver.LU_solver(A,b)
print(x)
print(np.matmul(A,x))

[0.17391304 0.00173913 0.67826087]
[1.2 2.4 5.6]


In [1]:
# decompose a symmetric matrix using Cholesky LU 
from myMath.linear_algebra import linear_system_solver
import numpy as np
A=np.array([[3,2,1],[2,10,3],[1,3,8]])
linear_solver=linear_system_solver()
U=linear_solver.Cholesky(A)
print(U)
print(np.matmul(U.T,U))

[[1.73205081 1.15470054 0.57735027]
 [0.         2.94392029 0.79259392]
 [0.         0.         2.6530099 ]]
[[ 3.  2.  1.]
 [ 2. 10.  3.]
 [ 1.  3.  8.]]


In [1]:
# chasing method
from myMath.linear_algebra import linear_system_solver
import numpy as np
linear_solver=linear_system_solver()
a=np.array([-1,-1])
b=np.array([4,4,4])
c=np.array([-1,-1])
y=np.array([2,4,10])

x=linear_solver.chasing(a,b,c,y)
print(x)


[1. 2. 3.]
