In [5]:
# Gaussian Elimination
import numpy as np
from myMath.linear_algebra import linear_system_solver
linear_solver=linear_system_solver()
A=np.array([[12,2,0],[1,8,2],[1,5,10]])
b=np.array([1,2,3])
x=linear_solver.gaussian_elimination(A,b)
print(x)
print(np.dot(A,x))
print(b)


[0.06547619 0.10714286 0.125     ]
[1.         1.17261905 1.85119048]
[1 2 3]


In [2]:
# Jacobi method:

import numpy as np
from myMath.linear_algebra import linear_system_solver
linear_solver=linear_system_solver()
A=np.array([[12,2,0],[1,8,2],[1,5,10]])
b=np.array([1,2,3])
x=linear_solver.jacobi(A,b)
print(x)
print(np.matmul(A,x))

[0.05096992 0.19417217 0.1978124 ]
[0.99998341 1.99997208 2.99995478]


In [1]:
# Gauss-Seidel method:

import numpy as np
from myMath.linear_algebra import linear_system_solver
linear_solver=linear_system_solver()
A=np.array([[12,2,0],[1,8,2],[1,5,10]])
b=np.array([1,2,3])
x=linear_solver.gauss_seidel(A,b)
print(x)
print(np.matmul(A,x))

[0.05097068 0.19417488 0.19781549]
[0.99999793 2.00000071 3.        ]


In [1]:
# LU decomposition:
import numpy as np
A=np.array([[2,1,5],[4,1,12],[-2,-4,5]])
L=np.zeros((3,3))
U=np.zeros((3,3))
for i in range(3):
    L[i,i]=1
U[0,:]=A[0,:] # first row of U is the first row of A
L[1:,0]=A[1:,0]/A[0,0] # first column of L is the first column of A divided by the first element of U
for k in range(1,3):
    for j in range(k,3):
        U[k,j]=A[k,j]-np.dot(L[k,:k],U[:k,j])
    for i in range(k+1,3):
        L[i,k]=(A[i,k]-np.dot(L[i,:k],U[:k,k]))/U[k,k]
print(L)
print(U)
print(np.matmul(L,U))
print(A)

[[ 1.  0.  0.]
 [ 2.  1.  0.]
 [-1.  3.  1.]]
[[ 2.  1.  5.]
 [ 0. -1.  2.]
 [ 0.  0.  4.]]
[[ 2.  1.  5.]
 [ 4.  1. 12.]
 [-2. -4.  5.]]
[[ 2  1  5]
 [ 4  1 12]
 [-2 -4  5]]


In [3]:
# LU decomposition
import numpy as np
from myMath.linear_algebra import linear_system_solver
A=np.array([[3,0,1],[2,10,3],[1,0,8]])
linear_solver=linear_system_solver()
L,U=linear_solver.LU(A)
print(L)
print(U)
print(np.matmul(L,U))
print(A)

[[1.         0.         0.        ]
 [0.66666667 1.         0.        ]
 [0.33333333 0.         1.        ]]
[[ 3.          0.          1.        ]
 [ 0.         10.          2.33333333]
 [ 0.          0.          7.66666667]]
[[ 3.  0.  1.]
 [ 2. 10.  3.]
 [ 1.  0.  8.]]
[[ 3  0  1]
 [ 2 10  3]
 [ 1  0  8]]


In [4]:
# solve a linear system using LU decomposition
from myMath.linear_algebra import linear_system_solver
import numpy as np
A=np.array([[3,0,1],[2,10,3],[1,0,8]])
b=np.array([1.2,2.4,5.6])
linear_solver=linear_system_solver()
x=linear_solver.LU_solver(A,b)
print(x)
print(np.matmul(A,x))
print(b)

[0.17391304 0.00173913 0.67826087]
[1.2 2.4 5.6]
[1.2 2.4 5.6]


In [10]:
# decompose a symmetric matrix using Cholesky decomposition
import numpy as np
A=np.array([[3,0,1],[2,10,3],[1,0,8]])
n=A.shape[0]
U=np.zeros((n,n))
for i in range(n):
    U[i,i]=np.sqrt(A[i,i]-np.dot(U[:i,i],U[:i,i]))
    for j in range(i+1,n):
        U[i,j]=(A[i,j]-np.dot(U[:i,i],U[:i,j]))/U[i,i]

print(U)
print(np.matmul(U.T,U))
print(A)

[[1.73205081 0.         0.57735027]
 [0.         3.16227766 0.9486833 ]
 [0.         0.         2.60128174]]
[[ 3.  0.  1.]
 [ 0. 10.  3.]
 [ 1.  3.  8.]]
[[ 3  0  1]
 [ 2 10  3]
 [ 1  0  8]]


In [1]:
# decompose a symmetric matrix using Cholesky LU 
from myMath.linear_algebra import linear_system_solver
import numpy as np
A=np.array([[3,2,1],[2,10,3],[1,3,8]])
linear_solver=linear_system_solver()
U=linear_solver.Cholesky(A)
print(U)
print(np.matmul(U.T,U))

[[1.73205081 1.15470054 0.57735027]
 [0.         2.94392029 0.79259392]
 [0.         0.         2.6530099 ]]
[[ 3.  2.  1.]
 [ 2. 10.  3.]
 [ 1.  3.  8.]]


In [ ]:
# decompose a tridiagonal  matrix using LU decomposition
import numpy as np
A=np.array([[3,23,0,0,0,0],[1,34,43,0,0,0],[0,2,55,22,0,0],[0,0,3,18,3,0],[0,0,0,4,13,77],[0,0,0,0,5,56]],dtype=np.double)
n=A.shape[0]
L=np.zeros((n,n),dtype=np.double)
U=np.zeros((n,n),dtype=np.double)
for i in range(n-1):
    U[i,i+1]=A[i,i+1]

for i in range(n):
    L[i,i]=1

U[0,0]=A[0,0]

for i in range(1,n):
    L[i,i-1]=A[i,i-1]/U[i-1,i-1]
    U[i,i]=A[i,i]-L[i,i-1]*U[i-1,i]

print(L)
print(U)
print(np.matmul(L,U))
print(A)
    

[[1.         0.         0.         0.         0.         0.        ]
 [0.33333333 1.         0.         0.         0.         0.        ]
 [0.         0.07594937 1.         0.         0.         0.        ]
 [0.         0.         0.05798874 1.         0.         0.        ]
 [0.         0.         0.         0.23917369 1.         0.        ]
 [0.         0.         0.         0.         0.40708395 1.        ]]
[[ 3.         23.          0.          0.          0.          0.        ]
 [ 0.         26.33333333 43.          0.          0.          0.        ]
 [ 0.          0.         51.73417722 22.          0.          0.        ]
 [ 0.          0.          0.         16.72424761  3.          0.        ]
 [ 0.          0.          0.          0.         12.28247893 77.        ]
 [ 0.          0.          0.          0.          0.         24.6545361 ]]
[[ 3. 23.  0.  0.  0.  0.]
 [ 1. 34. 43.  0.  0.  0.]
 [ 0.  2. 55. 22.  0.  0.]
 [ 0.  0.  3. 18.  3.  0.]
 [ 0.  0.  0.  4. 13. 77.]

In [2]:
import numpy as np
A=np.array([[3,23,0,0,0,0],[1,34,43,0,0,0],[0,2,55,22,0,0],[0,0,3,18,3,0],[0,0,0,4,13,77],[0,0,0,0,5,56]],dtype=np.double)
y=np.array([1,2,3,4,5,6],dtype=np.double)
n=A.shape[0]
u=np.zeros((n,),dtype=np.double)
v=np.zeros((n,),dtype=np.double)
x=np.zeros((n,),dtype=np.double)
u[0]=y[0]/A[0,0]
v[0]=A[0,1]/A[0,0] 

for i in range(1,n-1):
    u[i]=(y[i]-A[i,i-1]*u[i-1])/(A[i,i]-A[i,i-1]*v[i-1])
    v[i]=A[i,i+1]/(A[i,i]-A[i,i-1]*v[i-1])

u[-1]=(y[-1]-A[-1,-2]*u[-2])/(A[-1,-1]-A[-1,-2]*v[-2])

x[-1]=u[-1]
for i in range(n-2,-1,-1):
    x[i]=u[i]-v[i]*x[i+1]

print(x)
print(np.matmul(A,x))
print(y)


[-1.4126902   0.2277422  -0.10071034  0.36743565 -0.77057022  0.17594377]
[1. 2. 3. 4. 5. 6.]
[1. 2. 3. 4. 5. 6.]


In [1]:
# chasing method
from myMath.linear_algebra import linear_system_solver
import numpy as np
linear_solver=linear_system_solver()
a=np.array([-1,-1])
b=np.array([4,4,4])
c=np.array([-1,-1])
y=np.array([2,4,10])

x=linear_solver.chasing(a,b,c,y)
print(x)


[1. 2. 3.]
