### Lagrange Interplation

In [2]:
import numpy as np
from myMath.interpolation import intp_1d
intp=intp_1d()

x=np.array([1.0,2,3,5,6,8, 12.0])
y=np.array([0.2,0.4,0.7,1.1,2.1,4.5,9.5])
x_input=4.5

print(intp.Lagrange(x,y,x_input))

# for multple points interpolation, use numpy array!
x_input=np.array([1.2,4.5,7.3])
print(intp.Lagrange(x,y,x_input))

0.8601177793560606
[0.15110688 0.86011778 3.90518674]


### Newton's Divided Difference

In [1]:
import numpy as np
from myMath.interpolation import intp_1d
intp=intp_1d()

x=np.array([1.0,2,3,5,6,8, 12.0])
y=np.array([0.2,0.4,0.7,1.1,2.1,4.5,9.5])
x_input=4.5

print(intp.NewtonDD(x,y,x_input))

# for multple points interpolation, use numpy array!
x_input=np.array([1.2,4.5,7.3])
print(intp.NewtonDD(x,y,x_input))

0.8601177793560606
[0.15110688 0.86011778 3.90518674]


In [3]:
import numpy as np
from myMath.interpolation import intp_1d
intp=intp_1d()

x=np.array([10,30,40,60])
y=np.array([1407.17,1060.13,527.02,4.41E-12])
x_input=55

print(intp.NewtonDD(x,y,x_input))

# for multple points interpolation, use numpy array!
x_input=np.linspace(55,60,100)
for xi in x_input:
    print(xi,intp.NewtonDD(x,y,xi))


-14.293749999997317
55.0 -14.293749999997317
55.05050505050505 -14.793959200202607
55.101010101010104 -15.282061818828424
55.15151515151515 -15.758025433394778
55.2020202020202 -16.221817621420996
55.25252525252525 -16.673405960428
55.303030303030305 -17.112758027935342
55.35353535353536 -17.53984140146258
55.4040404040404 -17.954623658529272
55.45454545454545 -18.35707237665656
55.505050505050505 -18.747155133363776
55.55555555555556 -19.124839506170247
55.60606060606061 -19.49009307259621
55.656565656565654 -19.842883410162813
55.707070707070706 -20.18317809638802
55.75757575757576 -20.510944708793204
55.80808080808081 -20.826150824897468
55.85858585858586 -21.128764022221276
55.90909090909091 -21.418751878284183
55.95959595959596 -21.69608197060643
56.01010101010101 -21.96072187670734
56.06060606060606 -22.21263917410738
56.111111111111114 -22.451801440326108
56.16161616161616 -22.678176252884214
56.21212121212121 -22.891731189300344
56.26262626262626 -23.092433827095647
56.31313131

### Hermite Interpolation

In [10]:
# 2 pnts formula
import numpy as np
from myMath.interpolation import intp_1d
intp=intp_1d()
x=np.array([30,45,60])
y=np.array([0.5,0.707107,0.866025])
yp=np.array([0.866025,0.707107,0.5])
x_input=40
print(intp.Hermite_2pts(x[:2],y[:2],yp[:2],x_input))


0.044313703703703355


In [9]:
# 3 pnts formula
import numpy as np
from myMath.interpolation import intp_1d
intp=intp_1d()
x=np.array([30,45,60])
y=np.array([0.5,0.707107,0.866025])
yp=np.array([0.866025,0.707107,0.5])
x_input=40
print(intp.Hermite_3pts(x,y,yp[1],x_input))

-2.445046185185186


### spline interpolation

In [2]:
import numpy as np
from myMath.interpolation import intp_1d
intp=intp_1d()

x=np.array([1.0,2,3,5,6,8, 12.0])
y=np.array([0.2,0.4,0.7,1.1,2.1,4.5,9.5])
x_input=4.5

print(intp.spline(x,y,x_input,0))

# for multple points interpolation, use numpy array!
x_input=np.array([1.2,4.5,7.3])
print(intp.spline(x,y,x_input))

0.8646329488778055
[0.2315204  0.86463295 3.64791328]
